lobby:
arena: 
#************************************************
#             MEGA PVP CONFIG
#************************************************
//Plugin by EmreTr1
//TEst Server: minedogs.noip.me Port:19132
//...
